- id: '1702318795989'
  alias: Lamp woonkamer bij weinig licht
  description: Zet lamp woonkamer aan als iemand thuis komt en er weinig licht is
  trigger:
  - platform: state
    entity_id:
    - group.familie
    from: not_home
    to: home
  condition:
  - condition: numeric_state
    entity_id: sensor.buienradar_irradiance
    value_template: '{{ states.sensor.buienradar_irradiance.state | float(0) }}'
    below: 20
  action:
  - type: turn_on
    device_id: 8ad727d53106abb9f376ac840116127c
    entity_id: 516d27021a315d46c8506124605c65e3
    domain: light
  mode: single
- id: '1702356991153'
  alias: Lamp woonkamer uit als niemand thuis
  description: ''
  trigger:
  - platform: state
    entity_id:
    - group.familie
    from: home
    to: not_home
  condition: []
  action:
  - type: turn_off
    device_id: 8ad727d53106abb9f376ac840116127c
    entity_id: 516d27021a315d46c8506124605c65e3
    domain: light
  mode: single
- id: '1702454683861'
  alias: Lamp woonkamer uit als familie aanwezig
  description: Lamp woonkamer kan weer uit als familie terugkeerde en het te donker
    was. Inmiddels zal er wel een andere lamp aan zijn. :-)
  trigger:
  - platform: device
    type: turned_on
    device_id: 8ad727d53106abb9f376ac840116127c
    entity_id: 516d27021a315d46c8506124605c65e3
    domain: light
    for:
      hours: 0
      minutes: 22
      seconds: 0
  condition:
  - condition: state
    entity_id: group.familie
    state: home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
  - type: turn_off
    device_id: 8ad727d53106abb9f376ac840116127c
    entity_id: 516d27021a315d46c8506124605c65e3
    domain: light
  mode: single
- id: '1702716930715'
  alias: Rook in de schuur
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.rookmelder_schuur_hoeveelheid_rook
    above: 0
  condition: []
  action:
  - service: notify.mobile_app_dicks_iphone_14_pm
    data:
      message: Er is rook gedetecteerd in de schuur
      title: Rook in de schuur
      data: sensor.rookmelder_schuur_hoeveelheid_rook
  mode: single
- id: '1702717029691'
  alias: Koolmonoxide gedetecteerd in washok
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.koolmonoxidemelder_veiligheid
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_dicks_iphone_14_pm
    data:
      message: Koolmonoxide gedetecteerd in washok
      title: Koolmonoxide gedetecteerd in washok
  mode: single
- id: '1702717156497'
  alias: Verwarming aan in het weekend
  description: ''
  trigger:
  - platform: time
    at: 08:30
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  - condition: state
    entity_id: group.familie
    state: home
  action:
  - service: climate.set_temperature
    data:
      temperature: 19
    target:
      device_id: 98c3b36b898511c3fea646621ada9808
  - device_id: 98c3b36b898511c3fea646621ada9808
    domain: climate
    entity_id: 2a8a5adb988a6ba3dfa4ed7fe15e4899
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1702717190088'
  alias: Verwarming aan op werkdag
  description: ''
  trigger:
  - platform: time
    at: 07:30
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: group.familie
    state: home
  action:
  - service: climate.set_temperature
    data:
      temperature: 18.5
      hvac_mode: heat_cool
    target:
      device_id: 98c3b36b898511c3fea646621ada9808
  - device_id: 98c3b36b898511c3fea646621ada9808
    domain: climate
    entity_id: 2a8a5adb988a6ba3dfa4ed7fe15e4899
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1702717425031'
  alias: Plug AV-apparatuur uit als niemand thuis
  description: ''
  trigger:
  - platform: state
    entity_id: group.familie
    to: not_home
    for:
      minutes: 5
  condition:
  action:
  - service: switch.turn_off
    entity_id: switch.schakelaar_av_apparatuur
  mode: single
- id: '1702717458848'
  alias: Plug AV-apparatuur aan als iemand thuis
  description: ''
  trigger:
  - platform: state
    entity_id: group.familie
    from: not_home
    to: home
  condition:
  action:
  - service: switch.turn_on
    entity_id: switch.schakelaar_av_apparatuur
  mode: single
- id: '1702717827603'
  alias: Telefoon Dick bijna opgeladen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.dicks_iphone_14_pm_battery_level
    from: '94'
    to: '95'
  condition: []
  action:
  - service: notify.mobile_app_dicks_iphone_14_pm
    data:
      message: Batterij iPhne Dick bijna vol
  mode: single
- id: '1702717900856'
  alias: Ipad Dick bijna opgeladen
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ipad_van_dick_battery_level
    from: '94'
    to: '95'
  condition: []
  action:
  - service: notify.mobile_app_dicks_iphone_14_pm
    data:
      message: iPad Dick bijna opgeladen
  mode: single
- id: '1702717937329'
  alias: Afval meldingen
  description: ''
  trigger:
  - platform: time
    at:
    - 07:45:00
    id: Vandaag_today
  - platform: time
    at:
    - '17:00:00'
    id: Morgen_tomorrow
  - platform: time
    at:
    - '20:00:00'
    id: Morgen_tomorrow
  condition:
  - alias: Notification needed?
    condition: template
    value_template: '{{ states(sensor) != ''Geen'' }}'
  action:
  - alias: Notification phones
    service: notify.mobile_app_dicks_iphone_14_pm
    data:
      title: Denk aan de {{ states(sensor) }} container
      message: '{{ trigger.id.split(''_'')[0] }} moet {{ states(sensor) }} naar buiten'
      data:
        channel: Trash
        ttl: 0
        priority: high
        actions:
        - action: MARK_TRASH_MOVED
          title: Afval verwerkt
          icon: sfsymbols:trash.circle
  mode: single
  max_exceeded: silent
  variables:
    sensor: sensor.afvalwijzer_{{ trigger.id.split('_')[1] }}
- id: '1702887207212'
  alias: iPhone Dick bijna opgeladen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.dicks_iphone_14_pm_battery_level
    from: '94'
    to: '95'
  condition: []
  action:
  - service: notify.mobile_app_dicks_iphone_14_pm
    data:
      message: iPad Dick bijna opgeladen
  mode: single
- id: '1703160070212'
  alias: Purge database
  description: ''
  trigger:
  - platform: time
    at: 03:03:00
  condition: []
  action:
  - service: recorder.purge_entities
    data:
      entity_globs: sensor.buienradar* sensor.fritz* button.* light.*
      keep_days: 14
  mode: single
- id: '1703769617583'
  alias: Lamp werkkamer aan bij beweging
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 1d8ecd6d6cd2c63681b72206bec5802a
    entity_id: f3e04c6ad621f5f7af36631c6275ebd7
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: light.lamp_werkkamer
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.buienradar_irradiance
    below: 12
  action:
  - service: light.turn_on
    data: {}
    target:
      device_id: 3cf12c7a76df80b2aeffb6fb78ccf12b
  mode: single
- id: '1703769667924'
  alias: Lamp werkkamer uit als buiten licht genoeg
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.buienradar_irradiance
    value_template: '{{ states.sensor.buienradar_irradiance.state | float(0) }}'
    above: 12
  condition:
  - condition: state
    entity_id: light.lamp_werkkamer
    state: 'on'
  action:
  - service: light.turn_off
    data: {}
    target:
      device_id: 3cf12c7a76df80b2aeffb6fb78ccf12b
  mode: single
- id: '1703769748912'
  alias: Lamp werkkamer aan als buiten te donker
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.buienradar_irradiance
    value_template: '{{ states.sensor.buienradar_irradiance.state | float(0) }}'
    below: 12
  condition:
  - condition: time
    weekday:
    - fri
    enabled: false
  - condition: time
    before: '17:00:00'
  - condition: device
    type: is_off
    device_id: 3cf12c7a76df80b2aeffb6fb78ccf12b
    entity_id: ca0c051514f84f4149df1a5015face3d
    domain: light
  - condition: device
    type: is_on
    device_id: b1afc181b68a97e323db444f4597d846
    entity_id: bbf8e3c3e64e4e4f550d9d38161ed35a
    domain: switch
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.lamp_werkkamer
  mode: single
- id: '1703796513529'
  alias: Plug woonkamer uit als er geen activiteit is
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.plug_woonkamer_apparatuur_vermogen
    for:
      hours: 0
      minutes: 10
      seconds: 0
    below: 20
  condition: []
  action:
  - type: turn_off
    device_id: 1adc2f4f30cc1c3788d3f35e46e2c2bc
    entity_id: 276d4b8d1dcfc562d5f9b799b858e66e
    domain: switch
  mode: single
- id: '1703796619692'
  alias: Plug werkkamer uit bij geen activiteit
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.plug_werkkamer_vermogen
    for:
      hours: 0
      minutes: 10
      seconds: 0
    below: 30
  condition: []
  action:
  - type: turn_off
    device_id: b1afc181b68a97e323db444f4597d846
    entity_id: bbf8e3c3e64e4e4f550d9d38161ed35a
    domain: switch
  mode: single
- id: '1703862628084'
  alias: Lamp werkkamer uit als er weinig activiteit is
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 3cf12c7a76df80b2aeffb6fb78ccf12b
    entity_id: ca0c051514f84f4149df1a5015face3d
    domain: light
  condition:
  - condition: numeric_state
    entity_id: sensor.plug_werkkamer_vermogen
    below: 30
  action:
  - service: light.turn_off
    data: {}
    target:
      device_id:
      - 5ff71e054a09bc6eb13a83f806166252
      - 8ad727d53106abb9f376ac840116127c
  mode: single
- id: '1704015390920'
  alias: Melding wasmachine gereed
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.plug_wasmachine_vermogen
    for:
      hours: 0
      minutes: 10
      seconds: 0
    below: 1
  condition: []
  action:
  - service: notify.mobile_app_dicks_iphone_14_pm
    data:
      message: Was is gereed
  mode: single
- id: '1704018815195'
  alias: Plug werkkamer aan als accu laptop bijna leeg is
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.laptop_dick_batterijpercentage
    below: 25
  condition: []
  action:
  - type: turn_on
    device_id: b1afc181b68a97e323db444f4597d846
    entity_id: bbf8e3c3e64e4e4f550d9d38161ed35a
    domain: switch
  mode: single
- id: '1704033868674'
  alias: Melding vaatwasser gereed
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.plug_vaatwasser_vermogen
    for:
      hours: 0
      minutes: 10
      seconds: 0
    below: 6
  condition: []
  action:
  - service: notify.mobile_app_dicks_iphone_14_pm
    data:
      message: Vaatwasser is gereed
  mode: single
- id: '1704297141493'
  alias: Lamp werkkamer uit bij geen beweging
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 1d8ecd6d6cd2c63681b72206bec5802a
    entity_id: f3e04c6ad621f5f7af36631c6275ebd7
    domain: binary_sensor
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition:
  - condition: state
    entity_id: light.lamp_werkkamer
    state: 'on'
  action:
  - service: light.turn_off
    target:
      entity_id: []
      device_id:
      - 3cf12c7a76df80b2aeffb6fb78ccf12b
      area_id: []
    data: {}
  mode: single
- id: '1705216542367'
  alias: Verwarming aan in de avond
  description: ''
  trigger:
  - platform: time
    at: '18:00'
  condition:
  - condition: state
    entity_id: group.familie
    state: home
  action:
  - service: climate.set_temperature
    data:
      temperature: 19
    target:
      device_id: 98c3b36b898511c3fea646621ada9808
  - device_id: 98c3b36b898511c3fea646621ada9808
    domain: climate
    entity_id: 2a8a5adb988a6ba3dfa4ed7fe15e4899
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1705216795669'
  alias: Verwarming aan in de avond als Emilie thuis is
  description: ''
  trigger:
  - platform: time
    at: '18:00'
  condition:
  - condition: state
    entity_id: group.familie
    state: home
  - condition: state
    entity_id: person.emilie_pluim
    state: home
  action:
  - service: climate.set_temperature
    data:
      temperature: 19.5
    target:
      device_id: 98c3b36b898511c3fea646621ada9808
  - device_id: 98c3b36b898511c3fea646621ada9808
    domain: climate
    entity_id: 2a8a5adb988a6ba3dfa4ed7fe15e4899
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1705577740904'
  alias: Verwarming uit op werkdag
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition:
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - service: climate.set_temperature
    data:
      temperature: 18
      hvac_mode: 'off'
    target:
      device_id: 98c3b36b898511c3fea646621ada9808
  mode: single
- id: '1705577779941'
  alias: Verwarming uit in weekend
  description: ''
  trigger:
  - platform: time
    at: '22:30'
  condition:
  - condition: time
    weekday:
    - fri
    - sat
  action:
  - service: climate.set_temperature
    data:
      temperature: 18
    target:
      device_id: 98c3b36b898511c3fea646621ada9808
  mode: single
- id: '1705577815078'
  alias: Verwarming uit als niemand thuis
  description: ''
  trigger:
  - platform: state
    entity_id: group.familie
    from: home
    to: not_home
  condition:
  action:
  - service: climate.set_temperature
    data:
      temperature: 18
    target:
      device_id: 98c3b36b898511c3fea646621ada9808
  mode: single
- id: '1705596084966'
  alias: Kerstverlichting overkapping aan
  description: ''
  trigger:
  - platform: time
    at: 06:45:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      device_id: fbb19895d1ebfff19f07588ec33954bd
  mode: single
- id: '1705596251803'
  alias: Kerstverlichting aan bij zonsondergang
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: +00:30:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      device_id: fbb19895d1ebfff19f07588ec33954bd
  mode: single
- id: '1705596388141'
  alias: Kerstverlichting overkapping uit na zonsopkomst
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: -00:30:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id: fbb19895d1ebfff19f07588ec33954bd
  mode: single
- id: '1705596471666'
  alias: Kerstverlichting overkapping uit
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id: fbb19895d1ebfff19f07588ec33954bd
  mode: single
- id: '1705992029557'
  alias: Wasmachine aan bij voldoende zon
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.zonnepanelen_actuele_opbrengst
    above: 400
  condition:
  - condition: device
    type: is_off
    device_id: 0eaff47347d8e86ce73ea73db675198e
    entity_id: c63e17c8c7ff75b85c3d8a1727276be8
    domain: switch
  - condition: time
    after: '12:30:00'
  action:
  - type: turn_on
    device_id: 0eaff47347d8e86ce73ea73db675198e
    entity_id: c63e17c8c7ff75b85c3d8a1727276be8
    domain: switch
  - service: notify.mobile_app_dicks_iphone_14_pm
    metadata: {}
    data:
      message: Wasmachine gaat aan
      title: Wasmachine gaat aan
  mode: single
- id: '1706087379533'
  alias: Vaatwasser aan bij voldoende zon in winter
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.zonnepanelen_actuele_opbrengst
    above: 400
  condition:
  - condition: device
    type: is_off
    device_id: 0bd644fdb9c2b33937b560f64c070356
    entity_id: 49f29d2ad59ab7a2875866b4b6c158ef
    domain: switch
  action:
  - type: turn_on
    device_id: 0bd644fdb9c2b33937b560f64c070356
    entity_id: 49f29d2ad59ab7a2875866b4b6c158ef
    domain: switch
  - service: notify.mobile_app_dicks_iphone_14_pm
    metadata: {}
    data:
      message: Vaatwasser gaat aan
      title: Vaatwasser gaat aan
  mode: single
- id: '1708361476640'
  alias: Verwarming aan als iemand thuis overdag
  description: ''
  trigger:
  - platform: state
    entity_id: group.familie
    from: not_home
    to: home
  condition:
  - condition: time
    after: 08:30:00
    before: '18:00:00'
  action:
  - service: climate.set_temperature
    entity_id: climate.thermostaat
    data:
      temperature: 19
  - device_id: 98c3b36b898511c3fea646621ada9808
    domain: climate
    entity_id: 2a8a5adb988a6ba3dfa4ed7fe15e4899
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1708361535929'
  alias: Verwarming aan als iemand thuis avond
  description: ''
  trigger:
  - platform: state
    entity_id: group.familie
    from: not_home
    to: home
  condition:
  - condition: time
    after: '18:00:00'
    before: '22:00:00'
  action:
  - service: climate.set_temperature
    data:
      temperature: 19
    target:
      device_id: 98c3b36b898511c3fea646621ada9808
  - device_id: 98c3b36b898511c3fea646621ada9808
    domain: climate
    entity_id: 2a8a5adb988a6ba3dfa4ed7fe15e4899
    type: set_hvac_mode
    hvac_mode: heat
  mode: single
- id: '1708361608666'
  alias: Honeywell Lyric Fix
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /5
  - platform: state
    entity_id: climate.thermostaat
    to: unavailable
  condition:
  - condition: state
    entity_id: climate.thermostaat
    state: unavailable
  action:
  - service: homeassistant.update_entity
    entity_id: climate.thermostaat
  mode: single
- id: '1709449595343'
  alias: Vaatwasser aan bij voldoende zon vanaf maart
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.zonnepanelen_actuele_opbrengst
    above: 1000
  condition:
  - condition: device
    type: is_off
    device_id: 0bd644fdb9c2b33937b560f64c070356
    entity_id: 49f29d2ad59ab7a2875866b4b6c158ef
    domain: switch
  action:
  - type: turn_on
    device_id: 0bd644fdb9c2b33937b560f64c070356
    entity_id: 49f29d2ad59ab7a2875866b4b6c158ef
    domain: switch
  - service: notify.mobile_app_dicks_iphone_14_pm
    metadata: {}
    data:
      message: Vaatwasser gaat aan
      title: Vaatwasser gaat aan
  mode: single
- id: '1709449709736'
  alias: Wasmachine aan bij voldoende zon vanaf maart
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.zonnepanelen_actuele_opbrengst
    above: 1000
  condition:
  - condition: device
    type: is_off
    device_id: 0eaff47347d8e86ce73ea73db675198e
    entity_id: c63e17c8c7ff75b85c3d8a1727276be8
    domain: switch
  - condition: time
    after: '12:30:00'
  action:
  - type: turn_on
    device_id: 0eaff47347d8e86ce73ea73db675198e
    entity_id: c63e17c8c7ff75b85c3d8a1727276be8
    domain: switch
  - service: notify.mobile_app_dicks_iphone_14_pm
    metadata: {}
    data:
      message: Wasmachine gaat aan
      title: Wasmachine gaat aan
  mode: single
