# camera.yaml
# v2022.01.02
#
# History:
#
# v2022.01.02 - Initial version
#
# This file contains my cameras
#
- platform: ezviz
  username: !secret main_emailaddress
  password: !secret ezviz_password
  cameras:
    E25011134:
      username: admin
      password: !secret ezviz_cam_chalet
