# device_track.yaml
# v2022.01.03
#
# History:
#
# v2022.01.02 - Initial version
# v2022.01.03 - Moved ip-addresses to secrets.yaml
#
# This file contains my automations
#

# device-tracking to check if people are away or at home
# I use this method as not everyone wants to install the HomeAssistant app
#
- platform: ping
  interval_seconds: 30
  consider_home: 300
  hosts:
    telefoon_dick: !secret ip_dick
    telefoon_emilie: !secret ip_emilie
    telefoon_inge: !secret ip_inge
    telefoon_michel: !secret ip_michel
