# aanwezigheid.yaml
# v2022.01.03
#
# History:
#
# v2022.01.02 - Initial version
# v2022.01.03 - Added comment
#
# This file contains automations with respect to presence of family-members
# This is derived from the automation by Phil Hawthorne: https://philhawthorne.com/making-home-assistants-presence-detection-not-so-binary/
#

# check aan/afwezigheid

- alias: Markeer persoon als net thuis
  id: markeer_persoon_als_net_thuis
  trigger:
    - platform: state
      entity_id: device_tracker.telefoon_dick
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.telefoon_inge
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.telefoon_michel
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: device_tracker.telefoon_emilie
      from: 'not_home'
      to: 'home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.telefoon_dick' %}
            input_select.status_dick_dropdown
          {% elif trigger.entity_id == 'device_tracker.telefoon_inge' %}
            input_select.status_inge_dropdown
          {% elif trigger.entity_id == 'device_tracker.telefoon_emilie' %}
            input_select.status_emilie_dropdown
          {% elif trigger.entity_id == 'device_tracker.telefoon_michel' %}
            input_select.status_michel_dropdown
          {% endif %}
        option: Net thuis

- alias: Markeer persoon als thuis
  id: markeer_persoon_als_thuis
  trigger:
    - platform: state
      entity_id: input_select.status_dick_dropdown
      to: 'Net thuis'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.status_inge_dropdown
      to: 'Net thuis'
      for:
        minutes: 10 
    - platform: state
      entity_id: input_select.status_emilie_dropdown
      to: 'Net thuis'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.status_michel_dropdown
      to: 'Net thuis'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.status_dick_dropdown' %}
            input_select.status_dick_dropdown
          {% elif trigger.entity_id == 'input_select.status_inge_dropdown' %}
            input_select.status_inge_dropdown
          {% elif trigger.entity_id == 'input_select.status_emilie_dropdown' %}
            input_select.status_emilie_dropdown
          {% elif trigger.entity_id == 'input_select.status_michel_dropdown' %}
            input_select.status_michel_dropdown
          {% endif %}
        option: Thuis

- alias: Markeer persoon als net weg
  id: markeer_persoon_als_net_weg
  trigger:
    - platform: state
      entity_id: device_tracker.telefoon_dick
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.telefoon_inge
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.telefoon_emilie
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.telefoon_michel
      from: 'home'
      to: 'not_home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'device_tracker.telefoon_dick' %}
            input_select.status_dick_dropdown
          {% elif trigger.entity_id == 'device_tracker.telefoon_inge' %}
            input_select.status_inge_dropdown
          {% elif trigger.entity_id == 'device_tracker.telefoon_emilie' %}
            input_select.status_emilie_dropdown
          {% elif trigger.entity_id == 'device_tracker.telefoon_michel' %}
            input_select.status_michel_dropdown
          {% endif %}
        option: Net weg
 
- alias: Markeer persoon als afwezig
  id: markeer_persoon_als_afwezig
  trigger:
    - platform: state
      entity_id: input_select.status_dick_dropdown
      to: 'Net weg'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.status_inge_dropdown
      to: 'Net weg'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.status_emilie_dropdown
      to: 'Net weg'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.status_michel_dropdown
      to: 'Net weg'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.status_dick_dropdown' %}
            input_select.status_dick_dropdown
          {% elif trigger.entity_id == 'input_select.status_inge_dropdown' %}
            input_select.status_inge_dropdown
          {% elif trigger.entity_id == 'input_select.status_emilie_dropdown' %}
            input_select.status_emilie_dropdown
          {% elif trigger.entity_id == 'input_select.status_michel_dropdown' %}
            input_select.status_michel_dropdown
          {% endif %}
        option: Afwezig
 
- alias: Markeer persoon als langdurig afwezig
  id: markeer_persoon_als_langdurig_afwezig
  trigger:
    - platform: state
      entity_id: input_select.status_dick_dropdown
      to: 'Afwezig'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.status_inge_dropdown
      to: 'Away'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.status_emilie_dropdown
      to: 'Afwezig'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.status_michel_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.status_dick_dropdown' %}
            input_select.status_dick_dropdown
           {% elif trigger.entity_id == 'input_select.status_inge_dropdown' %}
            input_select.status_inge_dropdown
          {% elif trigger.entity_id == 'input_select.status_emilie_dropdown' %}
            input_select.status_emilie_dropdown
          {% elif trigger.entity_id == 'input_select.status_michel_dropdown' %}
            input_select.status_michel_dropdown
          {% endif %}
        option: Langdurig afwezig

