# automations.yaml
# v2023.12.16
#
# History:
#
# v2022.01.02 - Initial version
# v2022.01.03 - Removed Honeywell Lyric-fix as it was already in verwarming.yaml
# v2022.01.09 - Minor change in garbage and removed a yet unused automation
#               Moved stuff to schakelaar.yaml
# v2022.01.11 - Added automation to get an alarm when phone and iPad are almost 
#               charged 
# v2022.01.17 - Notify-entries changed as no notifications where getting through
# v2022.05.30 - Modified mobile-app-service
# v2023.10.25 - Replaced Samsung A72 with iPhone
# v2023.12.16 - Removed some stuff and migrated some stuff to the GUI
#
# This file contains my automations
#

- id: '300m_van_huis'
  alias: Iemand is 300m van huis en op weg naar huis
  mode: single
  trigger:
  - platform: numeric_state
    entity_id:
      - proximity.dick_thuis
    below: 300
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: '{{ trigger.to_state.attributes.dir_of_travel  == "towards" }}'
  action:
  - service: notify.mobile_app_dick_iphone
    data_template:
      message: "{{trigger.to_state.object_id[:-5] | capitalize}} is 300m van huis!"


